name: kuttl tests
on:
  push:
    branches:
      - master
      - 1.10.x
    paths-ignore:
      - 'docs/**'
      - 'CHANGELOG/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'CHANGELOG/**'
jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-integ-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-integ-
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: false
          tags: k8ssandra/cass-operator:latest
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/k8ssandra-cass-operator.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: logger.Dockerfile
          push: false
          tags: k8ssandra/system-logger:latest
          outputs: type=docker,dest=/tmp/k8ssandra-system-logger.tar
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Upload cass-operator image
        uses: actions/upload-artifact@v2
        with:
          name: cass-operator
          path: /tmp/k8ssandra-cass-operator.tar
      - name: Upload system-logger image
        uses: actions/upload-artifact@v2
        with:
          name: system-logger
          path: /tmp/k8ssandra-system-logger.tar
  run_kuttl_tests:
    runs-on: ubuntu-latest
    needs: [build_docker_images]
    name: Run kuttl tests
    strategy:
      matrix:
        k8s_version: ["1.21"]
        kuttl-test:
        - test-cdc
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/checkout@v2
      if: github.event_name != 'pull_request'
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-  uses: docker/setup-buildx-action@v1
    - name: Kind kube-proxy issue workaround
      run: sudo sysctl net/netfilter/nf_conntrack_max=524288
    - name: Download cass-operator image
      uses: actions/download-artifact@v2
      with:
        name: cass-operator
        path: /tmp
    - name: Download system logger image
      uses: actions/download-artifact@v2
      with:
        name: system-logger
        path: /tmp
    - name: Load cass-operator image
      run: |
        docker load --input /tmp/k8ssandra-cass-operator.tar
    - name: Load system logger image
      run: |
        docker load --input /tmp/k8ssandra-system-logger.tar
    - name: Install kustomize
      run: |
        make kustomize
    - name: Install Helm
      run: |
        make bin/helm
    - name: Install kuttl
      run: |
        make bin/kubectl-kuttl
    - name: Create kind cluster
      run: |
        kind create cluster --name kind --config ./tests/kuttl/config/kind/w3k${{ matrix.k8s_version }}.yaml
        make IMG="k8ssandra/cass-operator:latest" docker-kind
    - name: Run kuttl test
      run: |
        # We are running tests against k8s 1.21
        # Additional versions must be added in kind config files under ./test/config/kind
        ./bin/kubectl-kuttl test --kind-context=kind --start-kind=false --test ${{ matrix.kuttl-test }}
    - name: Delete kind cluster
      run: |
        kind delete cluster --name kind